import config from "@iobroker/eslint-config";

export default [
  ...config,
  {
    languageOptions: {
      parserOptions: {
        projectService: { allowDefaultProject: ["*.mjs", "vitest.config.mts", "vitest.admin.config.mts"] },
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
      "jsdoc/require-jsdoc": "off",
      "jsdoc/require-param": "off",
      "jsdoc/require-param-description": "off",
      "jsdoc/no-blank-blocks": "off",
    },
  },
  {
    ignores: [
      // Session files of the note-taking hook: its cooldown marker
      // tmp/last-ndc.ts is a timestamp, not TypeScript — never lint them.
      ".remember/**",
      ".dev-server/",
      ".vscode/",
      "*.test.js",
      "test/*.js",
      "*.config.mjs",
      "build",
      "admin",
      "src-admin",
      "coverage",
      "node_modules",
      "scripts",
      "tasks.js",
      "**/adapter-config.d.ts",
      // Generated by `vite build` in src-admin/ next to every src/ module the card imports.
      "src/**/*.d.ts",
    ],
  },
];
